import { ICourse } from "../interfaces/general.interface";

export const COURSES_CONTENT: ICourse[] = [
	{
		id:  'js-backend',
		title: 'JS Backend',
		link: 'https://softuni.bg/trainings/2760/angular-january-2020',
		scopeItems: 2,
		gitHubLink: 'string',
		start: '14.01.2020',
		duration: 6,
	},
	{
		id: 'angular',
		title: 'Angular',
		link: 'https://softuni.bg/trainings/2760/angular-january-2020',
		scopeItems: 2,
		gitHubLink: 'string',
		start: '14.01.2020',
		duration: 6,
	},
	{
		id: 'css-advanced',
		title: 'CSS Advanced',
		link: 'https://softuni.bg/trainings/3042/css-advanced-july-2020',
		scopeItems: 2,
		gitHubLink: 'https://github.com/chavdarovae/07.CSS-Advanced-June-2019',
		start: '13.07.2020',
		duration: 4,
	},
	{
		id: 'html-and-css',
		title: 'HTML & CSS',
		link: 'https://softuni.bg/trainings/2375/html-and-css-may-2019',
		scopeItems: 2,
		gitHubLink: 'https://github.com/chavdarovae/06.HTML-CSS-May2019',
		start: '14.05.2019',
		duration: 7,
	},
	{
		id: 'js-applications',
		title: 'JS Applications',
		link: 'https://softuni.bg/trainings/2249/js-applications-march-2019',
		scopeItems: 2,
		gitHubLink: 'https://github.com/chavdarovae/05.JavaScript-Applications-March2019',
		start: '19.03.2019',
		duration: 4,
	},
	{
		id: 'js-advanced',
		title: 'JS Advanced',
		link: 'https://softuni.bg/trainings/2248/js-advanced-february-2019',
		scopeItems: 2,
		gitHubLink: 'https://github.com/chavdarovae/05.JavaScript-Applications-March2019',
		start: '12.02.2019',
		duration: 4,
	},
	{
		id: 'js-fundamentals',
		title: 'JS Fundamentals',
		link: 'https://softuni.bg/trainings/2247/js-fundamentals-january-2019',
		scopeItems: 2,
		gitHubLink: 'https://github.com/chavdarovae/03.JavaScript-Fundamentals-January2019',
		start: '15.01.2019',
		duration: 4,
	},
	{
		id: 'js-essentials',
		title: 'Technology Essentials - JavaScript',
		link: 'https://softuni.bg/trainings/2247/js-fundamentals-january-2019',
		scopeItems: 2,
		gitHubLink: 'https://github.com/chavdarovae/02.JavaScript-Essentials-September2018',
		start: '26.09.2018',
		duration: 12,
	},
	{
		id: 'pb-c',
		title: 'Programming Basics with C#',
		link: 'https://softuni.bg/trainings/1962/programming-basics-with-csharp-may-2018',
		scopeItems: 2,
		gitHubLink: '',
		start: '12.05.2018',
		duration: 4,
	},
	{
		id: 'pb-java',
		title: 'Programming Basics with JAVA',
		link: 'https://softuni.bg/trainings/1962/programming-basics-with-csharp-may-2018',
		scopeItems: 2,
		gitHubLink: '',
		start: '12.02.2019',
		duration: 4,
	}
];
