import { ICourse } from "../interfaces/general.interface";

export const COURSES_CONTENT: ICourse[] = [
	{
		id:  'js-backend',
		title: 'JS Backend',
		focus: 'practical skills for building Single Page Application & basic TypeScript',
		link: 'https://softuni.bg/trainings/2760/angular-january-2020',
		scope: [
			'Introduction to Angular and TypeScript',
			'Components and Data binding',
		],
		gitHubLink: 'string',
		start: '14.01.2020',
		duration: 6,
	},
	{
		id: 'angular',
		title: 'Angular',
		focus: 'practical skills for building Single Page Application & basic TypeScript',
		link: 'https://softuni.bg/trainings/2760/angular-january-2020',
		scope: [
			'Introduction to Angular and TypeScript',
			'Components and Data binding',
		],
		gitHubLink: 'string',
		start: '14.01.2020',
		duration: 6,
	},
	{
		id: 'css-advanced',
		title: 'CSS Advanced',
		focus: 'modern frontend design and development with animations and icons for adaptive display on devices with different screen sizes.',
		link: 'https://softuni.bg/trainings/3042/css-advanced-july-2020',
		scope: [
			'CSS architecture - IT CSS',
			'CSS architecture - BEM',
			'SASS',
			'CSS transitions, animations and transformations',
			'CSS grid',
			'Building layouts',
			'CSS architecture - IT CSS',
			'CSS architecture - BEM',
			'SASS',
			'CSS transitions, animations and transformations',
			'CSS grid',
			'Building layouts',
		],
		gitHubLink: 'https://github.com/chavdarovae/07.CSS-Advanced-June-2019',
		start: '13.07.2020',
		duration: 4,
	},
	{
		id: 'html-and-css',
		title: 'HTML & CSS',
		focus: 'ractical skills in web development using HTML5 and CSS3 standard latest innovations.',
		link: 'https://softuni.bg/trainings/2375/html-and-css-may-2019',
		scope: [
			'Introduction to html & CSS',
			'HTML structure',
			'CSS & typography',
			'CSS box model',
			'Position & float',
			'Flexbox',
			'Working with forms',
			'Media queries',
		],
		gitHubLink: 'https://github.com/chavdarovae/06.HTML-CSS-May2019',
		start: '14.05.2019',
		duration: 7,
	},
	{
		id: 'js-applications',
		title: 'JS Applications',
		focus: 'practical skills for building well-structured Single Page Applications.',
		link: 'https://softuni.bg/trainings/2249/js-applications-march-2019',
		scope: [
			'REST services',
			'AJAX and jquery AJAX',
			'Asynchronous programming',
			'JS for frontend',
			'Templating',
			'Routing and architecture',
			'Single page application',
		],
		gitHubLink: 'https://github.com/chavdarovae/05.JavaScript-Applications-March2019',
		start: '19.03.2019',
		duration: 4,
	},
	{
		id: 'js-advanced',
		title: 'JS Advanced',
		focus: 'pdevelops algorithmic thinking and practical skills for DOM tree manipulation and Unit testing.',
		link: 'https://softuni.bg/trainings/2248/js-advanced-february-2019',
		scope: [
			'Advanced functions',
			'Unit testing',
			'JS classes',
			'Object composition',
			'jQuery',
			'DOM manipulations',
		],
		gitHubLink: 'https://github.com/chavdarovae/05.JavaScript-Applications-March2019',
		start: '12.02.2019',
		duration: 4,
	},
	{
		id: 'js-fundamentals',
		title: 'JS Fundamentals',
		focus: 'JS syntax and practical skills in manipulation with data types, operators, expressions, conditional constructions, loops and functions.',
		link: 'https://softuni.bg/trainings/2247/js-fundamentals-january-2019',
		scope: [
			'JS syntax and operators',
			'Document object model',
			'Functions and logic flow',
			'Arrays and matrices',
			'Strings and regexp',
			'Objects and JSON',
			'Dom events',
		],
		gitHubLink: 'https://github.com/chavdarovae/03.JavaScript-Fundamentals-January2019',
		start: '15.01.2019',
		duration: 4,
	},
	{
		id: 'js-essentials',
		title: 'Technology Essentials - JavaScript',
		focus: 'basic techniques and tools for practical programming beyond the writing of simple program constructions.',
		link: 'https://softuni.bg/trainings/2247/js-fundamentals-january-2019',
		scope: [
			'Basic syntax, conditional statements and loops',
			'Basic HTML',
			'Data types and variables',
			'Basic CSS',
			'Arrays',
			'Http basics',
			'Methods / functions',
			'Problem solving',
			'Lists / arrays advanced',
			'Bitwise operations',
			'Associative arrays',
			'Intro to computer science',
			'Objects and classes',
			'Database basics',
			'String and text processing',
			'Regular expressions',
			'Basic web',
			'Git and GitHub',
			'Basic CRUD',
			'QA fundamentals',
			'Web project',
			'Open-source introduction',
		],
		gitHubLink: 'https://github.com/chavdarovae/02.JavaScript-Essentials-September2018',
		start: '26.09.2018',
		duration: 12,
	},
	{
		id: 'pb-c',
		title: 'Programming Basics with C#',
		focus: 'Basic coding skills.',
		link: 'https://softuni.bg/trainings/1962/programming-basics-with-csharp-may-2018',
		scope: [
			'IDE',
			'Simple operations and calculations',
			'Conditional statements',
			'Loops',
			'Nested loops',
		],
		gitHubLink: '',
		start: '12.05.2018',
		duration: 4,
	},
	{
		id: 'pb-java',
		title: 'Programming Basics with JAVA',
		focus: 'Basic coding skills.',
		link: 'https://softuni.bg/trainings/1962/programming-basics-with-csharp-may-2018',
		scope: [
			'IDE',
			'Simple operations and calculations',
			'Conditional statements',
			'Loops',
			'Nested loops',
		],
		gitHubLink: '',
		start: '12.02.2019',
		duration: 4,
	}
];
